### ISSUE TITLE
Scalability and degrading performance issue when using optional constructor arguments with Unity (NuGet package version 2.1.505.2)

### ISSUE THREAD

**Issue by TrevorMcAlister** [devtrends/Unity.Mvc5#2]
This issue was discovered in a much earlier version of Unity (NuGet package version 2.1.505.2), but please can you verify that is not present in the latest release.
When using the optional constructor arguments (as seen below) on non-singleton services, during heavy load testing it was reviled that there is a significant degrading performance issue when using the optional argument verses using a populated argument.

```
<constructor>
    <param name="cacheFolderAbsoluteBasePath">
        <optional />
    </param>
</constructor>
```

The graph below is the page load times from 64 users each making page requests 4 times a minute for a duration of 4 hours. 
Average page load time is 99 seconds and climbing, even within the first 30 minutes page load times are growing to +40 seconds.

![tl_websiteperformance_64users4hours_testsfailed](https://cloud.githubusercontent.com/assets/6974186/8802923/0009fae2-2fbc-11e5-9838-17da04d7f6e9.png)

When the constructor argument is switched to a fixed value (as seen below) then the performance issue can be avoided, no other code change was made.
Note: For both of the load tests the constructor argument was not being used at all, the service was an empty class with just the one constructor argument.

```
<constructor>
    <param name="cacheFolderAbsoluteBasePath" value="empty" />
</constructor>
```

The graph below is the page load times from 64 users each making page requests 4 times a minute for a duration of 4 hours, after switching to using a fixed value. 
Average page load time is 0.51 seconds, after the initial startup performance hit the page load time never exceeds 10 seconds.
![tl_websiteperformance_64users4hours_testspassed](https://cloud.githubusercontent.com/assets/6974186/8802927/03b007fe-2fbc-11e5-878b-b687ae110f37.png)

**Comment by devtrends** [comment]
Closing old issues. This looks like a Unity issue rather than a Unity.MVC5 one.
