### ISSUE TITLE
Child Container does not always have HttpContext on async methods

### ISSUE THREAD

**Issue by brainwipe** [devtrends/Unity.Mvc5#3]
.NET 4.6.1 with MVC 5, I have an async method:

```
public async Task<ActionResult> RenderMyPartial(string viewName)
{
    var message = string.Empty;
    using (var sw = new StringWriter())
    {
        var viewResult = ViewEngines.Engines.FindPartialView(ControllerContext, viewName);
        var viewContext = new ViewContext(ControllerContext, viewResult.View, ViewData, TempData, sw);
        viewResult.View.Render(viewContext, sw);
        message = sw.GetStringBuilder().ToString();
    }

    return Json(new MyModel
    {
        renderedOutput = message;
    });
}
```

I get a Null Reference Exception in `Unity.Mvc5.UnityDependencyResolver.get_ChildContainer()`.

I believe what is happening is that the MVC ViewEngine uses the Unity.MVC5 dependency resolver to build up the Controller from the `ControllerContext`. When it does so, the `HttpContext` has already been disposed of (as it is async) and so it fails.

I have not managed a work-around, instead I needed to swap the Unity.MVC5 library with the official Microsoft one [Unity.MVC](https://www.nuget.org/packages/Unity.Mvc/).

This bug has been present since Unity.MVC3, it's reported on StackOverflow in Unity.MVC4.
http://stackoverflow.com/questions/21681247/unity-mvc-getservice-in-background-thread-throws-nullreferenceexception

**Comment by devtrends** [comment]
This is very old but I can't replicate this. There is no reason why HttpContext should be null when using async and when I use your code, it works fine. In your example, there is no async going on (the method signature is async and it returns Task but there isn't any await call). This works fine for me. Even if I add in an await call, it still works. 

Looking online, you can have issues if you do not have <httpRuntime targetFramework="4.5" /> in your web.config. As you say though, now that the Unity team have released a package, you can always use that if you are having issues.

The library is only meant for the MVC pipeline as it makes use of HttpContext so will not work when this is not available as in the case of the SO example.
