### ISSUE TITLE
Could not load file or assembly 'Microsoft.Practices.Unity.Configuration'

### ISSUE THREAD

**Issue by dnxit** [devtrends/Unity.Mvc5#6]
Hi I'm using this package (Unity.Mvc5 v1.3.0 with Unity 5.5.0) and resolving through web.config

```
<section name="unity" type="Microsoft.Practices.Unity.Configuration.UnityConfigurationSection, Microsoft.Practices.Unity.Configuration" />
 
<unity>
 	<container>
		<register type="Interface.IUnityDependencyResolver, Interface" mapTo="Infrastructure.UnityDependencyResolver, Infrastructure" />
	</container>
</unity>

public static void RegisterComponents()
{
	var container = new UnityContainer();
	container.LoadConfiguration();
}
```

An error occurred creating the configuration section handler for unity: Could not load file or assembly 'Microsoft.Practices.Unity.Configuration' or one of its dependencies. The system cannot find the file specified.

Kindly Advise

**Comment by devtrends** [comment]
Is Microsoft.Practices.Unity.Configuration present in your packages.config and if so, which version?

**Comment by dnxit** [comment]
If I use these versions it works fine 

```
<package id="Unity" version="4.0.1" targetFramework="net461" />
<package id="Unity.Mvc5" version="1.2.3" targetFramework="net461" />
```

even in this case there is no reference for Microsoft.Practices.Unity.Configuration in my packages.config

**Comment by devtrends** [comment]
Version 5 of Unity splits the project up into multiple different packages so when using that version, Microsoft.Practices.Unity.Configuration must be referenced if you use config based configuration. Unity.MVC5 version 1.3 is written to work with this new version. The previous version of Unity.MVC5 (1.2.3) works with the older version of Unity (version 4) where everything (including file based config) is all contained in one big NuGet. Hope this helps.

**Comment by dnxit** [comment]
I tried your suggestion still its the same issue 

```
<package id="Unity" version="5.5.0" targetFramework="net461" />
<package id="Unity.Abstractions" version="3.0.0" targetFramework="net461" />
<package id="Unity.Configuration" version="5.1.2" targetFramework="net461" />
<package id="Unity.Mvc5" version="1.3.0" targetFramework="net461" />
```

Could not load file or assembly 'Microsoft.Practices.Unity.Configuration' or one of its dependencies. The system cannot find the file specified.

**Comment by dnxit** [comment]
it was the namespaces which have been changed for so called **Refactoring** the correct one for new version is 
`<section name="unity" type="Microsoft.Practices.Unity.Configuration.UnityConfigurationSection, Unity.Configuration" />`

**Comment by ben-pierre** [comment]
After hours of scouring the docs with this no where to be seen, and several guesses that were painfully close now that I've seen the solution, you have saved me. Thanks dnxit.
